apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::519935101128:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::519935101128:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-10Q2JS8SNM035
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-19T18:14:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1566"
  uid: bf4bf28b-6b62-4a0a-9fdd-d72b749be94a
