apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::519935101128:role/eksctl-hadhad-project-cluster-nod-NodeInstanceRole-QA8L7MJJKVV6
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::519935101128:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-19T12:31:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4809"
  uid: 95215e88-ddbb-4b02-ae5d-73f4e166385f
