apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: simple-jwt-api
  region: us-east-2
nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    minSize: 1
    maxSize: 2
    desiredCapacity: 1